### ISSUE TITLE
Broken import in crypto.go

### ISSUE THREAD

**Issue by tabacco** [SSLMate/go-pkcs12#1]
It looks like a local import path got committed in crypto.go: https://github.com/SSLMate/go-pkcs12/blob/master/crypto.go#L15

**Comment by tabacco** [comment]
Yep:
```go get github.com/SSLMate/go-pkcs12
package software.sslmate.com/src/go-pkcs12/internal/rc2: unrecognized import path "software.sslmate.com/src/go-pkcs12/internal/rc2" (parse https://software.sslmate.com/src/go-pkcs12/internal/rc2?go-get=1: no go-import meta tags ())```

**Comment by AGWA** [comment]
You need to `got get` and `import` the package using its canonical path, as reflected in the GoDoc: `software.sslmate.com/src/go-pkcs12`.  While the source is currently hosted on GitHub, this might change in the future.

**Comment by tabacco** [comment]
Okay, I'll fork. Thanks.

**Comment by AGWA** [comment]
If if you want to fork, go ahead, but it's not necessary.  `go get software.sslmate.com/src/go-pkcs12` should work.
