### ISSUE TITLE
pkcs12: expected exactly one certificate in the certBag

### ISSUE THREAD

**Issue by yuchanns** [SSLMate/go-pkcs12#11]
go newbie here, got some confusion.
```go
func main() {
	keyBytes, err := rsa.GenerateKey(rand.Reader, 1024)

	if err != nil {
		panic(err)
	}

	if err := keyBytes.Validate(); err != nil {
		panic(err)
	}

	dn := pkix.Name{
		Country:            []string{"EN"},
		Organization:       []string{"org"},
		OrganizationalUnit: []string{"org"},
		Locality:           []string{"city"},
		Province:           []string{"province"},
		CommonName:         "name",
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)

	template := x509.Certificate{
		Subject:            dn,
		SignatureAlgorithm: x509.SHA256WithRSA,
		SerialNumber:       serialNumber,
	}
	pfxBytes, err := pkcs12.Encode(rand.Reader, keyBytes, &template, []*x509.Certificate{}, pkcs12.DefaultPassword)

	if err != nil {
		panic(err)
	}

	_, _, err = pkcs12.Decode(pfxBytes, pkcs12.DefaultPassword)
	if err != nil {
		panic(err)  // I got: pkcs12: expected exactly one certificate in the certBag
	}
}
```
Did I make any mistake with the `pkcs12.Encode` or others? Many thanks

**Comment by AGWA** [comment]
[Per the GoDoc of `pkcs12.Decode`](https://godoc.org/software.sslmate.com/src/go-pkcs12#Decode):

> Decode extracts a certificate and private key from pfxData. This function assumes that there is only one certificate and only one private key in the pfxData. Since PKCS#12 files often contain more than one certificate, you probably want to use DecodeChain instead. 

Please let me know if that's unclear so I can improve the documentation if necessary.

**Comment by yuchanns** [comment]
> [Per the GoDoc of `pkcs12.Decode`](https://godoc.org/software.sslmate.com/src/go-pkcs12#Decode):
> 
> > Decode extracts a certificate and private key from pfxData. This function assumes that there is only one certificate and only one private key in the pfxData. Since PKCS#12 files often contain more than one certificate, you probably want to use DecodeChain instead.
> 
> Please let me know if that's unclear so I can improve the documentation if necessary.

The docs do not need improve since it's clearly enought. In fact I replace `pkcs12.Decode` as `pkcs12.DecodeChain` and still got the same err value.

**Comment by AGWA** [comment]
The problem is that you are not passing a properly-initialized `x509.Certificate` to `Encode`.  You need to create the `x509.Certificate` using a function such as [`x509.CreateCertificate`](https://golang.org/pkg/crypto/x509/#CreateCertificate) or [`x509.ParseCertificate`](https://golang.org/pkg/crypto/x509/#ParseCertificate).

**Comment by yuchanns** [comment]
> The problem is that you are not passing a properly-initialized `x509.Certificate` to `Encode`. You need to create the `x509.Certificate` using a function such as [`x509.CreateCertificate`](https://golang.org/pkg/crypto/x509/#CreateCertificate) or [`x509.ParseCertificate`](https://golang.org/pkg/crypto/x509/#ParseCertificate).

Oh that works fine! Thanks
