### ISSUE TITLE
How to export ecdsa privatekey as string from pfx ?

### ISSUE THREAD

**Issue by zenghuiLee** [SSLMate/go-pkcs12#15]
func Decode(pfxData []byte, password string) (privateKey interface{}, certificate *x509.Certificate, err error) 

how to write privateKey as sting to key file ?

**Comment by AGWA** [comment]
You can pass the returned `privateKey` to [`x509.MarshalPKCS8PrivateKey`](https://golang.org/pkg/crypto/x509/#MarshalPKCS8PrivateKey) to get a DER-encoded string.

You can pass the result of `x509.MarshalPKCS8PrivateKey` to [`pem.Encode`](https://golang.org/pkg/encoding/pem/#Encode) or [`pem.EncodeToMemory`](https://golang.org/pkg/encoding/pem/#EncodeToMemory) with a `Type` of `PRIVATE KEY` to produce a PEM-encoded private key file.

**Comment by zenghuiLee** [comment]
thanks,it works .
