### ISSUE TITLE
Customize FriendlyName for Export?

### ISSUE THREAD

**Issue by alindeman** [SSLMate/go-pkcs12#20]
Is it possible to provide a custom FriendlyName with `pcks.Export`, analogous to `openssl pcks12 -export -name "..."` ?

**Comment by pschou** [comment]
I don't know if you meant to leave this issue open, but I thought I would complete the issue by implementing a way of also reading out the friendly names from a trust store.  See #39

**Comment by AGWA** [comment]
Tracking this feature request in #34.
