### ISSUE TITLE
Cannot add friendly name to certificate properties?

### ISSUE THREAD

**Issue by bonbonr** [SSLMate/go-pkcs12#22]
Cannot add friendly name to certificate properties?
For more information, please see the content of the picturey.
![image](https://user-images.githubusercontent.com/74522447/110283998-0b2efb00-801c-11eb-8991-287ecaf51137.png)

**Comment by bonbonr** [comment]
`func Encode(rand io.Reader, privateKey interface{}, certificate *x509.Certificate, caCerts []*x509.Certificate, password string) (pfxData []byte, err error) {}`

- Encode function generates a PFX format certificate containing a private key for IIS web server. The friendly name cannot be displayed. Is it possible to customize the friendly name in the certificate properties?

- The friendly name can be customized or taken from the DNS Name (Common Name) in the x509 format certificate. Domain name information

**Comment by pschou** [comment]
@bonbonr Please see PR #39 as it adds the ability to set custom Friendlynames.

**Comment by AGWA** [comment]
Tracking this feature request in #34.
