### ISSUE TITLE
pkcs12: error reading P12 data: asn1: syntax error: indefinite length found (not DER)

### ISSUE THREAD

**Issue by subhanimshaik** [SSLMate/go-pkcs12#25]
When parsing the p12 file, hitting the above error, the same file can be decoded through web.
Any input as to what can be causing the issue.

**Comment by AGWA** [comment]
Per the package documentation:

> Note that only DER-encoded PKCS#12 files are supported, even though PKCS#12 allows BER encoding. This is because encoding/asn1 only supports DER.

**Comment by KaymeKaydex** [comment]
but it is not problem to write smth for pks12 ber support

**Comment by rodrigorodriguescosta** [comment]
is there any lib that support BER? many files I have, they are in DER and BER format, how to fix? how to convert BER in DER and than read with the package? does anyone knows?
