### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by rndd-github** [SSLMate/go-pkcs12#26]
Hi, i have to test this package before using, there is a problem.
go test software.sslmate.com/src/go-pkcs12 failed with status 2
src/software.sslmate.com/src/go-pkcs12/pkcs12_test.go:135:21: rsaPk.PublicKey.Equal undefined (type rsa.PublicKey has no field or method Equal)

**Comment by AGWA** [comment]
This package requires Go 1.15 or higher, as indicated in `go.mod`:

https://github.com/SSLMate/go-pkcs12/blob/c5206de65a786ab8e93fefbf6018fb374277c26a/go.mod#L3

If you upgrade to the latest version of Go, the tests will succeed.

**Comment by rndd-github** [comment]
ok, thank you




Aug 29, 2021, 19:00 by ***@***.***:
