### ISSUE TITLE
Java 18 PKCS12 keystore format

### ISSUE THREAD

**Issue by pivotal-david-osullivan** [SSLMate/go-pkcs12#28]
Java 18 migrates the `cacerts` keystore from JKS to a password-less PKCS12 format file. See the [release notes](https://www.oracle.com/java/technologies/javase/18all-relnotes.html) and [bug details](https://bugs.openjdk.java.net/browse/JDK-8275252).

When the data from this file is passed to `Decode*`, the library throws a `no MAC in data` [error](https://github.com/SSLMate/go-pkcs12/blob/1a24189a369eda03e87575d9e068b74946b71f9e/pkcs12.go#L384). The release notes also state: 
_"All certificates inside are not encrypted and there is no MacData for password integrity"_

Is it possible to add support for this new format?

**Comment by AGWA** [comment]
Could you attach an example password-less PKCS#12 file for testing?

**Comment by pivotal-david-osullivan** [comment]
[cacerts.zip](https://github.com/SSLMate/go-pkcs12/files/8425326/cacerts.zip)

This is from Amazon Corretto's Java 18 release!

**Comment by AGWA** [comment]
Thanks for the example file!  go-pkcs12@v0.2.0 will now decode password-less PKCS#12 files as long as the password argument is the empty string.
