### ISSUE TITLE
Encoding password-less PKCS12

### ISSUE THREAD

**Issue by pivotal-david-osullivan** [SSLMate/go-pkcs12#32]
Related to #28, in order to add cert entries to the JVM keystore in Java 18+, we also need to be able to encode with a blank password.

I have been using `EncodeTrustStoreEntries` with `""` as the password but when attempting to `Decode` this again I get [pkcs12: error reading P12 data: asn1: syntax error: sequence truncated](https://github.com/SSLMate/go-pkcs12/blob/18dc7b9430c99e109671045dbd9889389c8072d7/pkcs12.go#L367)

Is it possible to also add support for Encoding certs with `""` to store in a passwordless PKCS12 file?

**Comment by AGWA** [comment]
I can't reproduce that error.  Could you provide a test case?

**Comment by AGWA** [comment]
OK.  This will require a new API.  Regrettably, we added a second function for encoding trust stores only a month ago.  To make sure we don't have to keep adding new functions for this, we probably want some API like this:

```go
type TrustStoreOptions struct {
        HasPassword bool
        Password    string
}

func EncodeTrustStoreOptions(rand io.Reader, entries []TrustStoreEntry, options *TrustStoreOptions) ([]byte, error)
```

If `options` is nil, then sensible defaults (probably password-less) will be used.

I'm going to want to let this sit for a while to make sure we get the API right.

**Comment by pivotal-david-osullivan** [comment]
That sounds good thank you!

If you have a branch with this change or a nightly release I'd be happy to test it out before it's merged in.

**Comment by pschou** [comment]
Can you try #39 and see if this HasPassword option works for you?

**Comment by dmikusa** [comment]
I gave this a try and but had some issues. Let me walk through what I did, could just be me.

Here's my test app.

```
package main

import (
	"fmt"
	"os"

	"software.sslmate.com/src/go-pkcs12"
)

func main() {
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(fmt.Errorf("unable to open cacerts\n%w", err))
	}

	truststore := &pkcs12.TrustStore{}
	config := pkcs12.DefaultConfig.Clone()
	config.Password = ""
	err = pkcs12.UnmarshalTrustStore(data, truststore, config)
	if err != nil {
		panic(fmt.Errorf("unable to unmarshall cacerts\n%w", err))
	}

	fmt.Println("Had password?", config.HasPassword)
	for _, cert := range truststore.Entries {
		fmt.Println("Certs:", cert)
	}

        // if I set a password, I can list with keytool
	// config.HasPassword = true
	// config.Password = "foo"

	config.HasPassword = false
	data, err = pkcs12.MarshalTrustStore(truststore, config)
	if err != nil {
		panic(fmt.Errorf("unable to encode cacerts\n%w", err))
	}

	err = os.WriteFile(os.Args[2], data, 0644)
	if err != nil {
		panic(fmt.Errorf("unable to write cacerts\n%w", err))
	}
}
```

This uses the cacerts file from [Liberica JDK 19](https://www.bell-sw.com). Attaching for convenience.

We know it's a PKCS12 file, also interestingly when you run this command it does *not* prompt you for a password.

```
> keytool -list -keystore ./cacerts-liberica
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 152 entries
...
```

Now if I run the demo app against that `go run main.go ./cacerts-liberica ./cacerts-output`, it'll read & generate the new file & the file is a PKCS12 file.

The difference, and I believe this is what @pivotal-david-osullivan was getting at before, is that `keystore` prompts you for a password, whereas with the default file it does not prompt you. In addition, it does not accept an empty password so you can't list the PKCS12 file (it does work if I set an actual password).

At any rate, either there's something I didn't get right with the API to make a truly passwordless file or it's not quite working right.

The other odd thing is that I have to set `config.Password = ""` when Unmarshaling. If I don't, I get an error:

```
pkcs12: no MAC in data
```

[cacerts-liberica.gz](https://github.com/SSLMate/go-pkcs12/files/9661364/cacerts-liberica.gz)

**Comment by pschou** [comment]
Thank you for the example!  Very useful.

Please try this:
```
package main

import (
        "crypto/x509/pkix"
        "fmt"
        "os"

        "software.sslmate.com/src/go-pkcs12"
)

func main() {
        data, err := os.ReadFile(os.Args[1])
        if err != nil {
                panic(fmt.Errorf("unable to open cacerts\n%w", err))
        }

        truststore := pkcs12.NewTrustStoreWithPassword("")
        err = pkcs12.UnmarshalTrustStore(data, &truststore)
        if err != nil {
                panic(fmt.Errorf("unable to unmarshall cacerts\n%w", err))
        }

        //fmt.Printf("%+v\n", truststore)

        // When there is no password, this will return "nil" while
        // if a blank password is set it will return []
        fmt.Println("Had password?", truststore.Password)
        for _, cert := range truststore.Entries {
                fmt.Printf("Certs: %+v\n", cert)
        }

        // Setting a password takes two steps
        truststore.Password = []byte("MakeMyDay")

        // not encrypted still as if I set a password, it won't get put into play until an Algorithm is set
        truststore.CertBagAlgorithm = pkix.AlgorithmIdentifier{Algorithm: pkcs12.OidPBEWithSHAAnd40BitRC2CBC}
        truststore.MACAlgorithm = pkcs12.OidSHA1

        data, err = pkcs12.MarshalTrustStore(&truststore)
        if err != nil {
                panic(fmt.Errorf("unable to encode cacerts\n%w", err))
        }

        err = os.WriteFile(os.Args[2], data, 0644)
        if err != nil {
                panic(fmt.Errorf("unable to write cacerts\n%w", err))
        }
        // verify using:
        // $ keytool -list -keystore ./cacerts-output

        p12 := pkcs12.NewP12()
        for _, entry := range truststore.Entries {
                p12.CertEntries = append(p12.CertEntries, pkcs12.CertEntry{Cert: entry.Cert})
        }

        data, err = pkcs12.Marshal(&p12)
        if err != nil {
                panic(fmt.Errorf("unable to encode cacerts\n%w", err))
        }

        err = os.WriteFile(os.Args[3], data, 0644)
        if err != nil {
                panic(fmt.Errorf("unable to write cacerts\n%w", err))
        }
        // verify using:
        // $ openssl pkcs12 -in p12-output -info
}
```

**Comment by dmikusa** [comment]
Excellent! That is working for me, and it makes more clear the difference (i.e. not encrypted vs empty password).

No pressure, but for our planning purposes do you have an idea when you will cut a release with the above changes? Thanks

**Comment by pschou** [comment]
This would a call @AGWA would have to make.  I am contributing, but I am not an owner of this repository.

**Comment by pivotal-david-osullivan** [comment]
@AGWA Just wanted to follow up on this, do you have plans to incorporate the contribution that resolves this issue?
