### ISSUE TITLE
Support triple DES certificate encryption

### ISSUE THREAD

**Issue by Marc-Pons** [SSLMate/go-pkcs12#36]
OpenSSL 3 throws an error of legacy algorithm when trying to parse P12 that uses RC2 to encrypt its certificates.

I would like to have the ability to encrypt the certificates with triple DES when generating P12. Pretty much an equivalent to the "-descert" flag of openssl.

I have created a proposal for this functionality in https://github.com/SSLMate/go-pkcs12/pull/35.

Thanks.

**Comment by marc1161** [comment]
Any updates on this thread?

**Comment by pschou** [comment]
Can you try #39 and see if the with config / added asn1 option field fixes this support need?

**Comment by Marc-Pons** [comment]
@pschou Awesome, it works like a charm! It would be great if your PR https://github.com/SSLMate/go-pkcs12/pull/39 could be merged and I will proceed to close mine :)

**Comment by pschou** [comment]
I think I want to re-write the logic to make a P12 object to fill and write out...  Please stand by.

**Comment by pschou** [comment]
@Marc-Pons Do you mind pulling down the changes and trying out the refactored method?   I would value your feedback and any help you may be willing to give, specifically by providing example(s).

**Comment by pschou** [comment]
@marc1161  @Marc-Pons  Please take a look at the re-write.
