### ISSUE TITLE
Error in parsing encrypted private key

### ISSUE THREAD

**Issue by mailsanchu** [SSLMate/go-pkcs12#40]
I am getting the following error when I try to parse an encrypted key 
`panic: pkcs12: error parsing PKCS#8 private key: x509: PKCS#8 wrapping contained private key with unknown algorithm: 1.2.840.10040.4.1`

What could be the issue

**Comment by pedroalbanese** [comment]
@mailsanchu

You are trying to read a key with another algorithm, I believe the library only supports ECDSA and RSA.

```go
func PfxParse() error {
	pfxBytes, err := os.ReadFile(*cert)
	if err != nil {
		return err
	}
	_, certificate, err := pkcs12.Decode(pfxBytes, *pwd)
	if err != nil {
		return err
	}

	pemCert := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certificate.Raw})
	fmt.Printf("%s", pemCert)

	PEM, err := pkcs12.ToPEM(pfxBytes, *pwd)
	if err != nil {
		return err
	}
//	fmt.Printf("%s", pem.EncodeToMemory(PEM[1]))

	_, err = x509.ParsePKCS1PrivateKey(PEM[1].Bytes)
	if err != nil {
		keyBlock := &pem.Block{
			Type:  "EC PRIVATE KEY",
			Bytes: PEM[1].Bytes,
		}
		fmt.Printf("%s", pem.EncodeToMemory(keyBlock))
	} else {
		keyBlock := &pem.Block{
			Type:  "RSA PRIVATE KEY",
			Bytes: PEM[1].Bytes,
		}
		fmt.Printf("%s", pem.EncodeToMemory(keyBlock))
	}

	return nil
}
```

**Comment by mailsanchu** [comment]
My algorithm is
Key Algorithm:	DSA
![image](https://user-images.githubusercontent.com/32928538/216135343-0a88a845-7c8a-4b39-9dcf-19de1fb3a439.png)

**Comment by mailsanchu** [comment]
Is ECDSA different from DSA?

**Comment by pedroalbanese** [comment]
> Is ECDSA different from DSA?

Yes, they have quite different structures. ECDSA is based on scalar multiplication, it is an elliptic curve. If I'm not mistaken, DSA is based on modular exponentiation, that is, it is more similar to RSA.

However, regardless of the fact that the DSA algorithm is already obsolete, this library handles RSA and ECDSA as described in RFC 7292: PKCS #12 Personal Information Exchange Syntax v1.1

**Comment by mailsanchu** [comment]
Ok So I need to change my algorithm to either RSA or ECDSA? Are you aware of any go tools that implements DSA

**Comment by pedroalbanese** [comment]
> Ok So I need to change my algorithm to either RSA or ECDSA? 
For this tasks yes.

> Are you aware of any go tools that implements DSA
There are libraries that use it, but because it is a legacy. I believe that DSA is no longer used because it is a strictly digital signature algorithm and does not perform other functions such as asymmetric cryptography and key derivation function. DSA is falling out of favor and has already been proven to be unsafe.

**Comment by pedroalbanese** [comment]
@mailsanchu

Disadvantages of using algorithms based on modular exponentiation:

### Key sizes
- **Bit-length Equivalence**

    | Symmetric Key Size  | RSA and DSA Key Size  | ECC Key Size   | 
    |:-------------------:|:---------------------:|:--------------:| 
    | 80                  | 1024                  | 160            | 
    | 112                 | 2048                  | 224            | 
    | 128                 | 3072                  | 256            | 
    | 192                 | 7680                  | 384            | 
    | 256                 | 15360                 | 512            |
