### ISSUE TITLE
Support decoding pbeWithSHAAnd128BitRC2CBC

### ISSUE THREAD

**Issue by vineet-garg** [SSLMate/go-pkcs12#43]
Currently library supports PBEWithSHAAnd40BitRC2CBC which generates 40 bit key
The library does not support pbeWithSHAAnd128BitRC2CBC which generates 128 bit key

Shall we add support for this algorithm.

**Comment by vineet-garg** [comment]
The PR: https://github.com/SSLMate/go-pkcs12/pull/39 seems to add support among other things.

**Comment by AGWA** [comment]
Hi @vineet-garg, could you provide some information about your use case?

Do you need to decode PKCS#12 files which use 128-bit RC2, and if so, what software is producing it?

Do you need to encode PKCS#12 files using 128-bit RC2, and if so, why? Could you use PBES2 with AES instead?

As I see it, there are only two sensible ways to use PKCS#12:

1. You pretend it's not encrypted at all, and protect private keys some other way (e.g. filesystem permissions), in which case it makes sense to use the ciphers with the most widespread support (which as I understand it, is RC2 with 40 bit keys for certificates, and 3DES for keys).
2. You use strong encryption, which is PBES2 with AES (which will soon be supported by go-pkcs12).

Thus, 128-bit RC2 doesn't seem like a necessary feature, so I'm looking for information that would convince me that it is.

**Comment by vineet-garg** [comment]
> Hi @vineet-garg, could you provide some information about your use case?
> 
> Do you need to decode PKCS#12 files which use 128-bit RC2, and if so, what software is producing it?
> 
> Do you need to encode PKCS#12 files using 128-bit RC2, and if so, why? Could you use PBES2 with AES instead?
> 
> As I see it, there are only two sensible ways to use PKCS#12:
> 
> 1. You pretend it's not encrypted at all, and protect private keys some other way (e.g. filesystem permissions), in which case it makes sense to use the ciphers with the most widespread support (which as I understand it, is RC2 with 40 bit keys for certificates, and 3DES for keys).
> 2. You use strong encryption, which is PBES2 with AES (which will soon be supported by go-pkcs12).
> 
> Thus, 128-bit RC2 doesn't seem like a necessary feature, so I'm looking for information that would convince me that it is.

Hi @AGWA Thank you for looking into this issue. My current use case is to decode PKCS#12 files that are encoded with 128-bit RC2. These are produced by internal cert generation and issuance tool which uses the algorithm to protect private keys. The tool uses PBE-SHA1-3DES and PBE-SHA1-RC2-128 based upon private key type chosen by the user and other interoperability requirements.

**Comment by AGWA** [comment]
Thanks for explaining your use case @vineet-garg.  I'll add decoding support for 128-bit RC2, but am going to hold off on encoding support.

**Comment by vineet-garg** [comment]
> Thanks for explaining your use case @vineet-garg. I'll add decoding support for 128-bit RC2, but am going to hold off on encoding support.

Thank you @AGWA , decoding support is sufficient and will be helpful.
