### ISSUE TITLE
HMAC with SHA512 not supported ? Error "unknown digest algorithm: 2.16.840.1.101.3.4.2.3" when decoding

### ISSUE THREAD

**Issue by hkailantzis** [SSLMate/go-pkcs12#59]
Hi there,

Is there any way to support decoding HMAC with SHA512 ? Trying to decode certs with HMAC 512, (using the DecodeChain or Decode function) but it throws the following error: "unknown digest algorithm: 2.16.840.1.101.3.4.2.3". 

Not a cert/crypto expert, so kinda confused, since it seems that https://pkg.go.dev/golang.org/x/crypto@v0.26.0/pbkdf2#pkg-overview supports HMAC 512, as in the 2.1 spec, but "to choose, you can pass the `New` functions from the different SHA packages to pbkdf2.Key" ? 

Happy to hear workarounds also, since other languages, like java etc already support HMAC with sha512.

Thanks in advance.

**Comment by AGWA** [comment]
Yeah, we can add support for this. Do you have a sample PKCS12 file that you could provide?

**Comment by tuxberlin** [comment]
@AGWA here is a p12 bag using sha512, generated by openssl 3.3.1
password is "abc"
[bag.zip](https://github.com/user-attachments/files/16819851/bag.zip)

**Comment by AGWA** [comment]
Thank you @tuxberlin !

**Comment by AGWA** [comment]
@hkailantzis could you try out the `sha512` branch to see if it works?

You can add it to your go.mod file by running:

```
go get software.sslmate.com/src/go-pkcs12@sha512
```

**Comment by hkailantzis** [comment]
@AGWA, thanks a ton! Works like a charm!. :-). Issue can be closed.

**Comment by hkailantzis** [comment]
@AGWA, thanks a ton! Works like a charm!. :-). Issue can be closed.
